### ISSUE TITLE
Minimize unnecessary dependencies when installing

### ISSUE THREAD

**Issue by maximecb** [MillionIntegrals/vel#29]
Hello! I'm trying to install vel to use with a custom OpenAI Gym environment that I'm creating.

I ran the command found in the README: `pip3 install vel[gym,mongo,visdom]`. Unfortunately, the install is repeatedly failing because of missing dependencies, and I'm having to hunt and peck to find which ones. In particular, the pillow and mujoco libraries are pulling in a lot of extra dependencies: zlib, cffi, Cython, jpeg, etc.

Currently, I feel like there are not many good options for RL in PyTorch. I would like to see something better take hold. I think that one way you could help vel gain traction is by making it easier to install. Minimize unnecessary dependencies, and you will help ensure that it doesn't fail to install when new users try it. Most people who try open source software, if it doesn't work out of the box, will just try something else and never look back. In my case, I have absolutely no need for mujoco environments. I don't think these should be installed by default. All I really want is to have access to a quality ppo implementation.

**Comment by maximecb** [comment]
On Ubuntu 18.04, the following need to be installed:
```
sudo apt-get install zlib1g-dev libjpeg-dev
pip3 install cffi
pip3 install cython
pip3 install lockfile
```

However, now it's asking me to install the actual mujoco package. This requires signing up for some 30-day trial on their website. Since I have no need for mujoco, I will stop here until a workaround is suggested.

**Comment by MillionIntegrals** [comment]
Hi, thank you for the information. It was definitely my goal for Mujoco not to be required for a simple installation. In the setup.py file that defines the dependencies, they look as follows:

```python
install_requires=[
        'attrs',
        'pyyaml',
        'numpy',
        'pandas',
        'scikit-learn',
        'torch == 0.4.1',
        'torchvision',
        'opencv-python',
        'pillow-simd',
        'tqdm'
    ],
    extras_require={
        'visdom': ['visdom'],
        'mongo': ['pymongo', 'dnspython'],
        'gym': ['gym[atari,box2d,classic_control]'],
        'mujoco': ['gym[mujoco,robotics]'],
        'dev': ['nose']
    },
```

Which I tried installing not only on my local machine but on several cloud machines and I didn't have to install mujoco there, because I didn't have the cloud license. As above, mujoco will be installed only if requested explicitly with pip install vel[mujoco].

You can also take a look at the dockerfile, that is used to install vel on the ubuntu image with pytorch/cuda preinstalled but no MuJoCo:

```dockerfile
FROM anibali/pytorch:cuda-9.2
MAINTAINER Jerry Tworek

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
USER user

# Install some basic utilities
RUN sudo apt-get update && sudo apt-get install -y gcc g++ make cmake zlib1g-dev swig libsm6 libxext6 && sudo rm -rf /var/lib/apt/lists/*

RUN pip install -U pip cython
COPY --chown=user:user . /vel
WORKDIR /vel
RUN pip install -e .[gym,mongo]
RUN mv .velproject.docker.yaml .velproject.yaml

CMD vel examples-configs/rl/atari/a2c/breakout_a2c.yaml train -d cuda:0
```

Let me know if you have any further troubles.

**Comment by MillionIntegrals** [comment]
Yeah, pillow could be a problem if it has any nonstandard dependencies. I'll see if I can strip that one a bit to something more minimal. 

Is there any particular dependency for pillow that is particularly problematic?

**Comment by maximecb** [comment]
They're not problematic for me right now, it's just, when people try to install your package, if they have to figure out which dependencies they need to install every time, you will lose some users. In my opinion, the real question is, do I need pillow to do RL training? What is it used for? But, I am a minimalist.

**Comment by MillionIntegrals** [comment]
Pillow is used more for vision models, that are included in the sourcecode as well. 

It's rather hard to include for everyone only exactly the packages they'll need, but I'll try to make some clearer instructions for sure.

**Comment by MillionIntegrals** [comment]
I have updated README with installation instructions and removed pillow-simd from project requirements and replaced it with original pillow which should have binary packages available for installation on most systems and thus present less problems to the users.
