### ISSUE TITLE
Understanding results from the ACER algorithm on Enduro

### ISSUE THREAD

**Issue by yngtodd** [MillionIntegrals/vel#35]
I came across some interesting results when running ACER on the Enduro environment when digging into hyperparameter optimization for this model. Here are the results of 50 runs for one particular set of hyperparameters:

![image](https://user-images.githubusercontent.com/16848331/49898740-d1b0ba80-fe27-11e8-9940-88c3b8da66b4.png)

I was a little bit surprised to see negative rewards here. Do you know how the Enduro environment can return negative rewards?

There was another curious case for the best configuration found through random search. I found that many of the evaluations only managed to run for a handful of frames. When running 50 runs of the environment in this case, only 12 runs made it past 1000 frames. Unfortunately all the rewards remained at 0.0 here. 

![image](https://user-images.githubusercontent.com/16848331/49899161-e93c7300-fe28-11e8-824e-ad2270505c67.png)

Would you have any recommendations for me to dig into why this particular configuration seems to fail often, and only returns 0.0 rewards for the remaining runs? If you are curious, here is the configuration I was using: [random search yaml](https://github.com/yngtodd/vel/blob/master/examples-configs/rl/atari/journal/acer/random_enduro_acer.yaml). And here are the [openai logging files](https://github.com/yngtodd/vel/tree/master/output/openai/hyperspace_enduro_acer).

**Comment by MillionIntegrals** [comment]
Hi Todd,

Sorry for the late replay but I just had a long christmas and new year holidays.

Question about your first graph: what is the actual thing you're plotting? If you're plotting just mean +/- std dev of various runs, then it's quite likely if the distribution is skewed to see that the graph goes slightly below zero even if you don't really see any negative rewards. 

As far as I can see you're quite lucky to get ACER running on enduro at all. If you look at my benchmarks on the blog: https://blog.millionintegrals.com/vel-pytorch-meets-baselines/ or from OpenAI baselines: https://github.com/openai/baselines/blob/master/benchmarks_atari10M.htm then you can see that ACER generally does not work at all on Enduro. 

As far as it seems, with current parametrizations I have only PPO and DQN work on that problem.

If the question is why, then I honestly don't know. If you learn anything about that I'd be quite interested in knowing. 

Few usual things to check would be:
- Exploration, maybe rewards are sparse enough that some algos just cannot reliably reach them? Possibly connected to the next one.
- Trust region/policy collapse - maybe for some algos policy quickly collapses into some pathological form it cannot recover from?
- Action and conseqence spread too far away: PPO in current parametrizations has the longest rollouts. Maybe that helps for the algorithm to correlate actions with rewards that happen much much later, and for other algos it's too far away.

These are just my guesses but let me know if you know anything more.

**Comment by yngtodd** [comment]
Hey MillionIntegrals,

No problem at all! I hope you had a great Christmas holiday. 

You are right, I am plotting the mean and standard deviation over 50 random seeds in that plot. I wasn't thinking about the skew making it look like those rewards were negative. Good call. 

I have been looking into hyperparameter optimization for RL algorithms and have been able to find a could configurations of ACER that work for Enduro. It has been a pretty interesting bit of work. These RL algorithms can be a bit of a handful when you start turning their knobs. Here is a plot from some of my work:

![image](https://user-images.githubusercontent.com/16848331/50915487-ea03fd00-1406-11e9-9026-fc0aeca1bfc0.png)

Not sure if I will be able to pin down why these particular configurations work, but I will let you know if I find out!

**Comment by MillionIntegrals** [comment]
Closing for now.
