### ISSUE TITLE
What is consideration regarding "FIRE" action in the env?

### ISSUE THREAD

**Issue by phizaz** [MillionIntegrals/vel#48]
I have seen this in `classic_atari.py`:

```
    if 'FIRE' in env.unwrapped.get_action_meanings():
        # Take action on reset for environments that are fixed until firing.
        if disable_episodic_life:
            env = FireEpisodicLifeEnv(env)
        else:
            env = FireResetEnv(env)
```

I don't know what's it for. Could you elaborate on this?
Update: I now know that some environments need some actions to really start after a reset.

Also, zooming out a bit I see:

```
    if not disable_episodic_life:
        # Make end-of-life == end-of-episode, but only reset on true game over.
        # Done by DeepMind for the DQN and co. since it helps value estimation.
        env = EpisodicLifeEnv(env)

    if 'FIRE' in env.unwrapped.get_action_meanings():
        # Take action on reset for environments that are fixed until firing.
        if disable_episodic_life:
            env = FireEpisodicLifeEnv(env)
        else:
            env = FireResetEnv(env)
```

The two if statements seem conflicting, doesn't it? I think if `EpisodicLifeEnv` is used, `FireEpisodicLifeEnv` also must be used.

**Comment by MillionIntegrals** [comment]
These wrappers are kind of independent, but they work on a similar underlying concept. 

- `EpisodicLifeEnv` - kind of as the name suggests, `end-of-life == end-of-episode`. In some games, (from the top of my head it's e.g. Montezuma's Revenge) each time you play you have several "lives". Generally the atari environment considers your episode finished when you lose all of those "lives". But as done in the DQN paper, it helps training the network if at least during policy training each of the "lives" is treated as a separate episode completely independent of the others.

- `FireResetEnv` and `FireEpisodicLifeEnv`- they are mostly independent, but there are some subtleties. In general, `FireResetEnv` presses `FIRE` action whenever an env resets. That's needed in e.g. Breakout to start the game. 

- `FireEpisodicLifeEnv` is a bugfix I've introduced myself and now I see the naming is super confusing. Basically what happens there is: If we're **not using** `EpisodicLifeEnv`, then there will be times when an agent loses life but are **not the end of episode**. At these times also game stops and waits for the `FIRE` action. So `FireEpisodicLifeEnv` is a wrapper similar to `FireResetEnv`, but in addition to pressing `FIRE` only when an env is reset also presses `FIRE` after an agent loses a life. This modification was needed for some environments to work.

Let me know if anything is still unclear.

**Comment by phizaz** [comment]
@MillionIntegrals That means if `EpisodicLifeEnv` is used, an agent must **learn** to `FIRE` action after a new life begins? because `FireResetEnv` is used and it won't `FIRE` if it is not explicitly reset. 

My intuition is in both scenarios `FireEpisodicLifeEnv` should be used, unless we want to force the agent to learn to start the game.

**Comment by MillionIntegrals** [comment]
It is slightly different. If `EpisodicLifeEnv` is used, whenever a new life begins an environment treats it as a completely new episode and `reset()` is called. Next wrapper `FireResetEnv` makes a `FIRE` action every time a `reset()` is called, therefore `FIRE` action is triggered automatically every time a new life begins as well as when a whole new game begins.

But if we don't have `EpisodicLifeEnv`, when a new life begins `reset()` is not called, therefore we need `FireEpisodicLifeEnv` that presses `FIRE` automatically both on `reset()` and when a new life starts.

**Comment by phizaz** [comment]
> treats it as a completely new episode and `reset()` is called.

@MillionIntegrals That's because a `vec_env` sees `done=True` and automatically resets the environment? That is correct albeit hard to get in the first read 😢.

**Comment by phizaz** [comment]
@MillionIntegrals  By the way, could you elaborate on why do we need to take two actions: 1 and 2 at the beginning of a new life?

```
            obs, _, done, _ = self.env.step(1)
            if done:
                self.env.reset()
            obs, _, done, _ = self.env.step(2)
            if done:
                self.env.reset()
```

**Comment by MillionIntegrals** [comment]
I'm not sure really, but I guess this is just needed by the env to restart after the new life. I've copied this bit from the preexisting OpenAI wrappers - `FireResetEnv`.
