### ISSUE TITLE
What's the reason behind using orthogonal weight initialization?

### ISSUE THREAD

**Issue by phizaz** [MillionIntegrals/vel#49]
I have see that you use `init.orthogonal_` exclusively everywhere. I don't think it is mentioned in any paper that I'm aware of (definitely not in Nature DQN paper). I want to understand more about the reasoning behind this decision. 

Thank you.

**Comment by MillionIntegrals** [comment]
Networks used for RL policies are generally shallow, so we don't care that much about gradient norm. The good thing about orthogonal initialization is that the columns of weight matrix are orthogonal to one another, which should encourage them to learn different features if possible. 

In general for most of these tasks, probably any reasonable initialization would work, but (without performing detailed experiments on the topic) I think orthogonal initialization should steer the SGD towards faster convergence by utilizing the weight matrix better for representing varied features.
