### ISSUE TITLE
Name error in stochastic_policy_rnn_model.py

### ISSUE THREAD

**Issue by yangysc** [MillionIntegrals/vel#50]
Thanks for your great work.  I found a small bug in the line of [104](https://github.com/MillionIntegrals/vel/blob/master/vel/rl/models/stochastic_policy_rnn_model.py) of stochastic_policy_rnn_model.py , the **key name** of returned value **logprobs** should be **'action:logprobs',** instead of **'logprobs'.**

**Comment by MillionIntegrals** [comment]
Fixed that now, thanks!
